apiVersion: v1
kind: Service
metadata:
  name: mongo-read
  namespace: ${NAMESPACE}
  labels:
    app: mongo
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - port: 27017
      name: mongo
